#!/bin/bash
################################################################################
# Stage 20: Network Configuration
# 
# usb0 設定、NAT、ファイアウォール適用
# ⭐【重要】ネットワーク変更検出＆再起動対応
################################################################################

set -euo pipefail
source "$(dirname "$0")/../_lib.sh"

main() {
    log_info "════════════════════════════════════════════"
    log_info "Stage 20: Network Configuration"
    log_info "════════════════════════════════════════════"
    
    # 1. usb0 インターフェース確認
    log_info "usb0 インターフェースをセットアップ..."
    setup_usb0
    
    # 2. dnsmasq リース用ディレクトリ
    log_info "dnsmasq リース用ディレクトリを準備..."
    mkdir -p /var/lib/dnsmasq
    touch /var/lib/dnsmasq/dnsmasq.leases
    chown nobody:nogroup /var/lib/dnsmasq/dnsmasq.leases

    # 3. 再起動前の DHCP ブートストラップ
    # Stage 20 後に再起動が入るため、--resume 前でも usb0 で DHCP を提供する。
    log_info "再起動前の DHCP を有効化..."
    local bootstrap_conf="/etc/dnsmasq.d/azazel-usb0-bootstrap.conf"
    cat > "$bootstrap_conf" <<'EOF'
# Auto-generated by Azazel installer Stage 20 (bootstrap only)
interface=usb0
bind-interfaces
listen-address=10.55.0.10
dhcp-range=10.55.0.50,10.55.0.200,255.255.255.0,5m
dhcp-authoritative
dhcp-option=option:router,10.55.0.10
dhcp-option=option:dns-server,10.55.0.10
dhcp-option-force=option:router,10.55.0.10
dhcp-option-force=option:dns-server,10.55.0.10
dhcp-leasefile=/var/lib/dnsmasq/dnsmasq.leases
EOF

    systemctl enable dnsmasq >> "$LOG_FILE" 2>&1 || \
        log_warn "dnsmasq の有効化に失敗（継続）"

    if systemctl restart dnsmasq >> "$LOG_FILE" 2>&1; then
        if ss -ulnH 'sport = :67' 2>/dev/null | grep -Fq "10.55.0.10:67"; then
            log_info "✓ DHCP ブートストラップ有効 (10.55.0.10:67)"
        else
            log_warn "⚠️  dnsmasq は起動したが DHCP(10.55.0.10:67) は未確認"
        fi
    else
        log_warn "⚠️  dnsmasq の再起動に失敗（--resume 前の DHCP が不安定な可能性）"
    fi
    
    # 4. NAT ルール適用（iptables）
    log_info "NAT ルールを適用..."
    if [[ -f "$PROJECT_ROOT/configs/iptables-rules.v4" ]] || [[ -f "$DEFAULTS_DIR/iptables-rules.v4" ]]; then
        local iptables_src="${DEFAULTS_DIR}/iptables-rules.v4"
        if [[ -f "$iptables_src" ]]; then
            iptables-restore < "$iptables_src" >> "$LOG_FILE" 2>&1 || die "iptables ルール適用失敗"
            log_info "✓ iptables ルール適用完了"
        fi
    fi
    
    # 5. IP フォワーディング有効化
    log_info "IP フォワーディングを有効化..."
    sysctl -w net.ipv4.ip_forward=1 >> "$LOG_FILE" 2>&1 || die "IP フォワーディング有効化失敗"

    # 5.5 USB ガジェット互換性（テザリング向け）
    # use_eem=0 にしてホストOS互換性を上げる（次回起動時に有効）
    log_info "USB ガジェット互換設定を適用..."
    mkdir -p /etc/modprobe.d
    cat > /etc/modprobe.d/g_ether.conf <<'EOF'
# Azazel-Zero: improve host-side compatibility for USB tethering
options g_ether use_eem=0
EOF
    
    # 6. nftables ベース設定（後の Stage 40 で systemd 経由で適用）
    # ここでは、usb0 に対する入力ルールをテスト
    log_debug "nftables 準備は Stage 40 で行います"
    
    # 7. 【重要】ネットワーク変更検出
    log_info ""
    log_info "═══════════════════════════════════════════════════════════"
    log_info "ネットワーク構成をチェック中..."
    log_info "═══════════════════════════════════════════════════════════"
    
    local wlan0_ip_before=$(get_state "wlan0_ip_before")
    local usb0_ip_before=$(get_state "usb0_ip_before")
    local wlan0_ip_after=$(get_interface_ip wlan0 || echo "unknown")
    local usb0_ip_after=$(get_interface_ip usb0 || echo "unknown")
    
    log_info "wlan0 (upstream) IP:"
    log_info "  Before: $wlan0_ip_before"
    log_info "  After:  $wlan0_ip_after"
    log_info "usb0 (downstream) IP:"
    log_info "  Before: $usb0_ip_before"
    log_info "  After:  $usb0_ip_after"

    # ネットワークが変わったか判定
    # usb0 変化を優先して判定（SSH/USB接続切断の主因）
    local network_changed=0
    if [[ "$usb0_ip_before" != "$usb0_ip_after" ]]; then
        network_changed=1
    fi
    if [[ "$wlan0_ip_before" != "unknown" ]] && \
       [[ "$wlan0_ip_after" != "unknown" ]] && \
       [[ "$wlan0_ip_before" != "$wlan0_ip_after" ]]; then
        network_changed=1
    fi

    if [[ "$network_changed" -eq 1 ]]; then
        
        log_warn ""
        log_warn "⚠️  ネットワーク構成が変更された可能性があります"
        log_warn "    wlan0: $wlan0_ip_before → $wlan0_ip_after"
        log_warn "    usb0:  $usb0_ip_before → $usb0_ip_after"
        log_warn ""
        
        # 再起動をプロンプト（自動再起動モード時は install.sh 側で実施）
        if [[ "${AUTO_REBOOT:-0}" == "1" ]]; then
            log_info "自動再起動モード: install.sh 側で再起動処理を行います"
        else
            prompt_reboot
        fi
        
        # 状態ファイルに記録
        set_state "stage" "20_NEEDS_REBOOT"
        
        log_info "再起動が必要です。"
        log_info "再起動後、以下を実行してください:"
        log_info "  sudo ./install.sh --resume"
        
        exit 0  # 正常に終了（エラーではない）
    fi
    
    log_info ""
    log_info "✓ ネットワーク構成に大きな変化なし（再起動不要）"
    log_info ""
    
    log_info "════════════════════════════════════════════"
    log_info "✓ Stage 20 完了"
    log_info "════════════════════════════════════════════"
    mark_stage_passed "20"
    return 0
}

main "$@"
