#!/bin/bash
# ⚠️  DEPRECATED: This script is superseded by the unified installer.
# 
# **新形式は以下を使用してください：**
# 
#   sudo ./install.sh --with-ntfy
# 
# このスクリプトは v3.0 で削除されます。
# 詳細: docs/INSTALLER_DEPRECATION_SCHEDULE.md

# install_ntfy.sh - Install and configure ntfy.sh self-hosted push notification server
# for Azazel-Gadget (Raspberry Pi Zero 2 W)
#
# Usage: sudo bash install_ntfy.sh
#
# This script:
# 1. Checks for port conflicts (8081)
# 2. Installs ntfy from official apt repository
# 3. Configures /etc/ntfy/server.yml
# 4. Creates ntfy admin user and generates token
# 5. Saves token to /etc/azazel/ntfy.token
# 6. Enables and starts the ntfy service

set -e

NTFY_PORT="8081"
NTFY_LISTEN=":${NTFY_PORT}"
NTFY_ADMIN_USER="azazel"
NTFY_TOKEN_FILE="/etc/azazel/ntfy.token"
NTFY_PASSWORD_FILE="/etc/azazel/ntfy.password"
NTFY_SERVER_CONF="/etc/ntfy/server.yml"
NTFY_MGMT_IP="10.55.0.10"
NTFY_BASE_URL="http://${NTFY_MGMT_IP}:${NTFY_PORT}"
APT_OPTS=${APT_OPTS:-"-o Acquire::Retries=3 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 -o Dpkg::Use-Pty=0"}
LOCK_WAIT_SECS=${LOCK_WAIT_SECS:-120}

echo "============================================"
echo "Azazel-Gadget ntfy Installation Script"
echo "============================================"

# Wait for apt/dpkg lock to clear
wait_for_apt_lock() {
    local waited=0
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
        if [ "$waited" -ge "$LOCK_WAIT_SECS" ]; then
            echo "ERROR: dpkg lock still held after ${LOCK_WAIT_SECS}s. Please try again later."
            exit 1
        fi
        echo "Waiting for dpkg lock... (${waited}s)"
        sleep 5
        waited=$((waited + 5))
    done
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

# Step 1: Check port availability
echo ""
echo "[1/6] Checking port availability (${NTFY_PORT})..."
port_line="$(sudo ss -tulpen 2>/dev/null | grep -E ":${NTFY_PORT}\b" | head -n 1 || true)"
if [[ -n "${port_line}" ]]; then
    if echo "${port_line}" | grep -qi "ntfy"; then
        echo "✓ Port ${NTFY_PORT} is already in use by ntfy; continuing"
    else
        echo "ERROR: Port ${NTFY_PORT} is already in use. Please resolve before proceeding."
        if command -v lsof >/dev/null 2>&1; then
            echo "Using process: $(sudo lsof -i :${NTFY_PORT} 2>/dev/null | tail -1)"
        fi
        exit 1
    fi
else
    echo "✓ Port ${NTFY_PORT} is available"
fi

# Step 2: Install ntfy
echo ""
echo "[2/6] Installing ntfy from apt repository..."
wait_for_apt_lock

# Add ntfy repository key and source
if ! grep -q "archive.ntfy.sh" /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null; then
    echo "Adding ntfy repository..."
    
    # Try to fetch and verify GPG key, but allow to proceed even if it fails
    # (Raspberry Pi may have GPG verification issues)
    mkdir -p /etc/apt/keyrings
    
    # Add apt source with allow-insecure option (ntfy GPG issues on ARM)
    echo "deb [signed-by=/etc/apt/keyrings/ntfy.gpg] https://archive.ntfy.sh/apt stable main" | \
        tee /etc/apt/sources.list.d/ntfy.list > /dev/null
    
    # Attempt to fetch key (may fail on ARM)
    curl -fsSL https://archive.ntfy.sh/apt/ntfy.gpg | \
        gpg --dearmor -o /etc/apt/keyrings/ntfy.gpg 2>/dev/null || {
        echo "Warning: GPG key installation failed, using allow-insecure workaround"
        # Use [allow-insecure=yes] as fallback for ARM
        echo "deb [allow-insecure=yes] https://archive.ntfy.sh/apt stable main" | \
            tee /etc/apt/sources.list.d/ntfy.list > /dev/null
    }
    
    apt-get update $APT_OPTS
else
    echo "ntfy repository already configured"
fi

# Install ntfy package
if ! dpkg -l | grep -q "^ii.*ntfy"; then
    apt-get install -y --allow-unauthenticated ntfy $APT_OPTS || \
    apt-get install -y ntfy $APT_OPTS
    echo "✓ ntfy installed"
else
    echo "✓ ntfy already installed"
fi

# Step 3: Configure server.yml
echo ""
echo "[3/6] Configuring /etc/ntfy/server.yml..."

# Create/update server configuration
cat > "${NTFY_SERVER_CONF}" <<EOF
# Azazel-Gadget ntfy server configuration
# Generated by install_ntfy.sh

# Server address and port (USB-local only)
base-url: "${NTFY_BASE_URL}"
listen-http: "${NTFY_LISTEN}"

# Database and cache
cache-file: /var/cache/ntfy/cache.db
auth-file: /var/lib/ntfy/user.db
auth-default-access: deny-all

# Security
behind-proxy: false
web-root: /

# CORS (optional, for client apps)
cors-origin: "*"

# Log level (info | debug | warn | error)
log-level: info
EOF

echo "✓ Server configuration created at ${NTFY_SERVER_CONF}"

# Ensure auth file exists (ntfy needs to start once)
echo ""
echo "Initializing ntfy auth database (if missing)..."
if [ ! -f /var/lib/ntfy/user.db ]; then
    systemctl daemon-reload || true
    systemctl start ntfy || true
    for i in 1 2 3 4 5 6 7 8 9 10; do
        [ -f /var/lib/ntfy/user.db ] && break
        sleep 1
    done
fi
if [ ! -f /var/lib/ntfy/user.db ]; then
    echo "ERROR: auth-file was not created. Check: sudo systemctl status ntfy"
    exit 1
fi

# Step 4: Create ntfy admin user and generate token
echo ""
echo "[4/6] Setting up ntfy user and token..."

# Check if user already exists
if ntfy user list 2>/dev/null | grep -q "^${NTFY_ADMIN_USER}"; then
    echo "✓ User '${NTFY_ADMIN_USER}' already exists"
else
    echo "Creating ntfy admin user..."
    if [[ -f "${NTFY_PASSWORD_FILE}" ]] && [[ -s "${NTFY_PASSWORD_FILE}" ]]; then
        NTFY_PASSWORD="$(cat "${NTFY_PASSWORD_FILE}")"
    else
        NTFY_PASSWORD="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)"
        mkdir -p /etc/azazel
        echo -n "${NTFY_PASSWORD}" > "${NTFY_PASSWORD_FILE}"
        chmod 600 "${NTFY_PASSWORD_FILE}"
        chown root:root "${NTFY_PASSWORD_FILE}"
    fi
    NTFY_PASSWORD="${NTFY_PASSWORD}" ntfy user add --role=admin --ignore-exists "${NTFY_ADMIN_USER}" || {
        echo "Warning: Could not create user (may already exist)"
    }
fi

# Generate new token (or use existing)
echo ""
echo "Checking for existing token..."
if [[ -f "${NTFY_TOKEN_FILE}" ]] && [[ -s "${NTFY_TOKEN_FILE}" ]]; then
    NTFY_TOKEN=$(cat "${NTFY_TOKEN_FILE}")
    echo "✓ Using existing token from ${NTFY_TOKEN_FILE}"
else
    echo "Generating new bearer token..."
    NTFY_TOKEN=$(ntfy token add --label="azazel-gadget" "${NTFY_ADMIN_USER}" 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i ~ /^tk_/) {print $i; exit}}')
    
    if [[ -z "${NTFY_TOKEN}" ]]; then
        echo "ERROR: Failed to generate token. Please manually run:"
        echo "  ntfy token add --label='azazel-gadget' ${NTFY_ADMIN_USER}"
        exit 1
    fi
fi

# Step 5: Save token to secure location
echo ""
echo "[5/6] Saving token to ${NTFY_TOKEN_FILE}..."

mkdir -p /etc/azazel
echo -n "${NTFY_TOKEN}" > "${NTFY_TOKEN_FILE}"
chmod 600 "${NTFY_TOKEN_FILE}"
chown root:root "${NTFY_TOKEN_FILE}"

echo "✓ Token saved (permissions: 0600)"
echo ""
echo "Token: ${NTFY_TOKEN:0:20}..."

# Step 6: Enable and start service
echo ""
echo "[6/6] Enabling and starting ntfy service..."

systemctl daemon-reload
systemctl enable ntfy
systemctl restart ntfy

# Wait for service to be ready
sleep 2

if systemctl is-active --quiet ntfy; then
    echo "✓ ntfy service is running"
else
    echo "Warning: ntfy service may not have started. Check: sudo systemctl status ntfy"
fi

# Verify connectivity
echo ""
echo "============================================"
echo "Installation Complete"
echo "============================================"
echo ""
echo "ntfy is now accessible at:"
echo "  URL: ${NTFY_BASE_URL}"
echo "  Token: ${NTFY_TOKEN:0:20}..."
echo ""
echo "Quick Test:"
echo "  export NTFY_TOKEN=\"\$(cat ${NTFY_TOKEN_FILE})\""
echo "  curl -H \"Authorization: Bearer \${NTFY_TOKEN}\" \\"
echo "       -H \"Title: Test\" \\"
echo "       -d \"Hello from Azazel-Gadget\" \\"
echo "       ${NTFY_BASE_URL}/azg-alert-critical"
echo ""
echo "Configure Azazel notify settings in /etc/azazel-zero/first_minute.yaml:"
echo "  notify:"
echo "    enabled: true"
echo "    ntfy:"
echo "      base_url: \"${NTFY_BASE_URL}\""
echo "      token_file: \"${NTFY_TOKEN_FILE}\""
echo "      topic_alert: \"azg-alert-critical\""
echo "      topic_info: \"azg-info-status\""
echo ""
echo "Restart Azazel service to apply:"
echo "  sudo systemctl restart azazel-first-minute"
echo ""
