#!/usr/bin/env bash
# Azazel-Zero bootstrap script
# Purpose: reproducible setup on Raspberry Pi Zero 2 W
# Usage: sudo tools/bootstrap_zero.sh [--no-epd] [--no-enable] [--no-suricata] [--dry-run]

set -euo pipefail

# ---------- defaults ----------
WITH_EPD=1
ENABLE_SERVICES=1
RUN_SURICATA_UPDATE=1
DISABLE_USB_AUTOSUSPEND=1
WITH_WEBUI=0  # Web UI is optional, use --with-webui to enable
LOG=${LOG:-/var/log/azazel-bootstrap.log}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AZAZEL_ROOT="${AZAZEL_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

# ---------- helpers ----------
log(){ echo "[+] $*" | tee -a "$LOG"; }
warn(){ echo "[!] $*" | tee -a "$LOG" >&2; }
fail(){ echo "[x] $*" | tee -a "$LOG" >&2; exit 1; }
require_root(){ if [ "${EUID:-$(id -u)}" -ne 0 ]; then fail "Run as root"; fi; }
cmd(){ echo "+ $*" | tee -a "$LOG"; eval "$@" | tee -a "$LOG"; }

# ---------- preflight checks (non-fatal) ----------
check_spi(){
  local cfg
  for cfg in /boot/config.txt /boot/firmware/config.txt; do
    if [ -f "$cfg" ]; then
      if grep -Eq '^\s*dtparam=spi=on' "$cfg"; then log "SPI appears enabled in $cfg"; return 0; fi
    fi
  done
  warn "SPI does not appear enabled (dtparam=spi=on not found). Enable via 'raspi-config'."
}

check_gadget(){
  local c1=/boot/firmware/cmdline.txt c2=/boot/cmdline.txt cfg1=/boot/firmware/config.txt cfg2=/boot/config.txt
  local cmdf="" cfgf=""
  for f in "$c1" "$c2"; do
    [ -f "$f" ] || continue
    if grep -q 'DO NOT EDIT THIS FILE' "$f" 2>/dev/null; then
      continue
    fi
    cmdf="$f"
    break
  done
  for f in "$cfg1" "$cfg2"; do
    [ -f "$f" ] || continue
    if grep -q 'DO NOT EDIT THIS FILE' "$f" 2>/dev/null; then
      continue
    fi
    cfgf="$f"
    break
  done
  if [ -n "$cfgf" ] && ! grep -Eq 'dtoverlay=dwc2' "$cfgf"; then warn "USB Gadget overlay missing in $cfgf (dtoverlay=dwc2)."; fi
  if [ -n "$cmdf" ] && ! grep -Eq 'modules-load=dwc2,g_ether' "$cmdf"; then warn "USB Gadget modules not found in $cmdf (modules-load=dwc2,g_ether)."; fi
}

disable_usb_autosuspend(){
  local cmdf=""
  for f in /boot/firmware/cmdline.txt /boot/cmdline.txt; do
    [ -f "$f" ] || continue
    if grep -q 'DO NOT EDIT THIS FILE' "$f" 2>/dev/null; then
      continue
    fi
    cmdf="$f"
    break
  done
  if [ -z "$cmdf" ]; then
    warn "cmdline.txt not found; skip usbcore.autosuspend=-1"
    return
  fi
  if grep -q 'usbcore.autosuspend=-1' "$cmdf"; then
    log "usbcore.autosuspend already set in $cmdf"
    return
  fi
  if grep -q 'usbcore.autosuspend=' "$cmdf"; then
    sed -i 's/usbcore\.autosuspend=[^ ]*/usbcore.autosuspend=-1/' "$cmdf"
    log "Updated usbcore.autosuspend in $cmdf"
  else
    sed -i 's/$/ usbcore.autosuspend=-1/' "$cmdf"
    log "Added usbcore.autosuspend=-1 to $cmdf"
  fi
}

# ---------- steps ----------
install_deps(){
  log "Installing dependencies (WITH_EPD=${WITH_EPD})"
  if [ "$WITH_EPD" -eq 1 ]; then
    cmd "bash $AZAZEL_ROOT/bin/install_dependencies.sh --all"
  else
    cmd "bash $AZAZEL_ROOT/bin/install_dependencies.sh"
  fi
}

install_systemd(){
  log "Installing systemd units"
  cmd "bash $AZAZEL_ROOT/bin/install_systemd.sh"
}

suricata_minimal(){
  if [ "$RUN_SURICATA_UPDATE" -eq 1 ]; then
    log "Configuring minimal Suricata rules"
    cmd "bash $AZAZEL_ROOT/bin/suricata_update.sh"
  else
    log "Skipping Suricata update"
  fi
}

install_webui(){
  if [ "$WITH_WEBUI" -eq 1 ]; then
    log "Installing Web UI components"
    cmd "bash $AZAZEL_ROOT/bin/install_webui.sh"
  else
    log "Skipping Web UI installation (use --with-webui to enable)"
  fi
}

enable_services(){
  if [ "$ENABLE_SERVICES" -eq 1 ]; then
    log "Enabling services"
    systemctl enable --now azazel-epd.service suri-epaper.service azazel-console.service || true
    systemctl enable --now opencanary.service || true
    if [ "$WITH_WEBUI" -eq 1 ]; then
      systemctl enable --now azazel-control-daemon.service || true
      log "Web UI control daemon enabled"
    fi
  else
    log "Skipping systemctl enable --now"
  fi
}

smoke_test(){
  log "Smoke test"
  systemctl is-active azazel-epd.service >/dev/null && log "EPD OK" || warn "EPD not active"
  systemctl is-active suri-epaper.service >/dev/null && log "suri-epaper OK" || warn "suri-epaper not active"
  if tmux ls 2>/dev/null | grep -q azazel; then log "tmux console OK"; else warn "tmux console missing"; fi
}

usage(){
  cat <<USAGE
Usage: sudo tools/bootstrap_zero.sh [OPTIONS]

Options:
  --no-epd               Skip E-Paper optional deps
  --no-enable            Do not enable/start services
  --no-suricata          Skip minimal Suricata rules
  --no-usb-autosuspend   Keep USB autosuspend enabled (do not edit cmdline.txt)
  --with-webui           Install Web UI components (Flask, control daemon)
  --dry-run              Show steps only
  -h, --help             Show this help message

Web UI (--with-webui):
  - Flask web server on port 8084
  - Remote monitoring dashboard
  - Control daemon for actions
  - USB gadget access: http://10.55.0.10:8084
USAGE
}

main(){
  # Parse arguments first (before root check for --help)
  local DRY=0
  for a in "$@"; do
    case "$a" in
      -h|--help)
        usage
        exit 0
        ;;
      --no-epd) WITH_EPD=0 ;;
      --no-enable) ENABLE_SERVICES=0 ;;
      --no-suricata) RUN_SURICATA_UPDATE=0 ;;
      --no-usb-autosuspend) DISABLE_USB_AUTOSUSPEND=0 ;;
      --with-webui) WITH_WEBUI=1 ;;
      --dry-run) DRY=1 ;;
      *) echo "[x] Unknown arg: $a"; exit 1 ;;
    esac
  done

  require_root
  mkdir -p "$(dirname "$LOG")" && : >"$LOG"

  log "Bootstrap start (AZAZEL_ROOT=$AZAZEL_ROOT)"
  check_spi
  check_gadget
  if [ "$DISABLE_USB_AUTOSUSPEND" -eq 1 ]; then
    disable_usb_autosuspend
  else
    log "Skipping usbcore.autosuspend change"
  fi

  if [ "$DRY" -eq 1 ]; then
    echo "Would run: disable_usb_autosuspend -> install_deps -> install_systemd -> suricata_minimal -> install_webui (if --with-webui) -> enable_services -> smoke_test"
    exit 0
  fi

  install_deps
  install_systemd
  suricata_minimal
  install_webui
  enable_services
  smoke_test
  log "Bootstrap complete"
}

main "$@"
